# Generated by Django 4.2.6 on 2023-11-12 07:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('developer', models.CharField(default='Unknown', max_length=200)),
                ('company_name', models.CharField(default='Unknown', max_length=200)),
                ('language', models.CharField(default='Unknown', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feature_image', models.ImageField(upload_to='assets/images/')),
                ('about', models.CharField(blank=True, default='Nothing', max_length=200)),
                ('description', models.TextField()),
                ('download_link', models.URLField(blank=True, null=True)),
                ('device', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('linux', 'Linux'), ('mac', 'Mac')], max_length=10)),
                ('total_downloads', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000000000), django.core.validators.MinValueValidator(0)])),
                ('on_created', models.DateTimeField()),
            ],
        ),
    ]
