# Generated by Django 4.2.6 on 2023-11-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('body', models.TextField(blank=True, null=True)),
                ('gamelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.gamelist')),
            ],
        ),
    ]
