# Generated by Django 4.2.6 on 2023-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0003_cons_pros_alter_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gamelist',
            name='cons',
            field=models.ManyToManyField(to='Games.cons'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='pros',
            field=models.ManyToManyField(to='Games.pros'),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='genera',
            field=models.ManyToManyField(to='Games.genera'),
        ),
    ]
