# Generated by Django 4.2.6 on 2023-11-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_genera_gamelist_cons_gamelist_pros_gamelist_genera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='feature_image',
            field=models.ImageField(default='assets/images/gameimages/default.png', upload_to='assets/images/gameimages'),
        ),
        migrations.CreateModel(
            name='AdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameimage', models.ImageField(default='assets/images/gameimages/default.png', upload_to='assets/images/gameimages')),
                ('gamelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.gamelist')),
            ],
        ),
    ]
