# Generated by Django 4.2.6 on 2023-11-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_alter_gamelist_feature_image_additionalimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelist',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='on_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='gamelist',
            new_name='game_list',
        ),
    ]
