# Generated by Django 4.2.6 on 2023-11-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_alter_gamelist_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimages',
            old_name='gameimage',
            new_name='game_image',
        ),
        migrations.RenameField(
            model_name='additionalimages',
            old_name='gamelist',
            new_name='game_list',
        ),
    ]
