# Generated by Django 4.2.6 on 2023-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0007_rename_gameimage_additionalimages_game_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalimages',
            old_name='game_image',
            new_name='game_list_image',
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
