# Generated by Django 4.2.6 on 2023-11-12 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0008_rename_game_image_additionalimages_game_list_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
