# Generated by Django 4.2.6 on 2023-11-12 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0009_gamelist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='size_mb',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=2, validators=[django.core.validators.MaxValueValidator(100000000.0), django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
