# Generated by Django 4.2.6 on 2023-11-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0012_reviews_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelist',
            options={'ordering': ['-total_downloads']},
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='Rating',
            new_name='rating',
        ),
    ]
