# Generated by Django 4.2.6 on 2023-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='profile_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(related_name='friends', to='Users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='assets/images/userimages/default.png', upload_to='assets/images/userimages'),
        ),
    ]
