# Generated by Django 4.2.6 on 2023-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_user_clip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_clip',
            name='user_clip',
            field=models.FileField(default='assests/videos/clip_video/default.mp4', upload_to='assests/videos/clip_video'),
        ),
    ]
