# Generated by Django 4.2.6 on 2023-11-13 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_clip_user_clip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_clip',
            options={'ordering': ['upload_date']},
        ),
        migrations.AddField(
            model_name='user_clip',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
