# Generated by Django 4.2.6 on 2023-11-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_clip_options_user_clip_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_clip',
            name='dislikes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_clip',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_clip',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
