# Generated by Django 4.2.6 on 2023-11-13 11:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_user_clip_dislikes_user_clip_likes_user_clip_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_clip',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='clip_title', unique=True),
            preserve_default=False,
        ),
    ]
